baseurl = "http://jess.bobmarquis.com"
title = "Jessica S. Marquis"

theme = "coder"

languagecode = "en"

publishDir = "docs"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Jessica S. Marquis"
    description = "Jessica S. Marquis' personal website"
    keywords = "blog,personal"
    info = "Faith + Justice mixed with Humor & Whimsy"

[[params.social]]
    name = "Twitter"
    weight = 1
    url = "https://twitter.com/bizette/"
[[params.social]]
    name = "Facebook"
    weight = 2
    url = "http://facebook.com/jessicadoesstuff/"
[[params.social]]
    name = "Amazon"
    weight = 3
    url = "https://www.amazon.com/Jessica-S.-Marquis/e/B005CADOH4/"
[[params.social]]
    name = "Goodreads"
    weight = 3
    url = "https://www.goodreads.com/author/show/4527822.Jessica_S_Marquis/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/jsmarquis/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Creations"
    weight = 1
    url  = "/creations/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
