baseURL = "http://dev.jessicasmarquis.com/"
languageCode = "en-us"
title = "Jessica S. Marquis"
theme = "minimal"

[permalinks]
  post = "/:year/:month/:title/"

[params]
    author = "Jessia S. Marquis"
    description = "Personal blog theme powered by Hugo"
    showBorder = true
    accent = "#40017F"
    accentLight = "rgba(106, 97, 195, .3)"
    backgroundColor = "white"
    font = "Open Sans" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/creations/"
    name = "Creations"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:jessica@jessicasmarquis.com"
    name = "fas fa-at"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/bizette/"
    name = "fab fa-twitter"
    weight = 2

[[menu.icon]]
    url = "http://facebook.com/jessicadoesstuff/"
    name = "fab fa-facebook"
    weight = 3

[[menu.icon]]
    url = "https://www.amazon.com/Jessica-S.-Marquis/e/B005CADOH4/"
    name = "fab fa-amazon"
    weight = 4

[[menu.icon]]
    url = "https://www.goodreads.com/author/show/4527822.Jessica_S_Marquis/"
    name = "fab fa-goodreads"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/jsmarquis/"
    name = "fab fa-linkedin"
    weight = 4